version: '3.8'

services:
  db:
    image: postgres:16
    container_name: map_db
    environment:
      POSTGRES_DB: map_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9632
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
    container_name: map_web
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./uploads:/usr/local/tomcat/webapps/map-app/static/uploads

volumes:
  pgdata:
